jindan.lo: /Users/liuli/work/pkg/php-5.6.7/ext/jindan/jindan.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/liuli/work/pkg/php-5.6.7/ext/jindan $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/liuli/work/pkg/php-5.6.7/ext/jindan/jindan.c -o jindan.lo 
$(phplibdir)/jindan.la: ./jindan.la
	$(LIBTOOL) --mode=install cp ./jindan.la $(phplibdir)

./jindan.la: $(shared_objects_jindan) $(JINDAN_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_jindan) $(JINDAN_SHARED_LIBADD)

