// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//屏蔽全部消息
type AllRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	Switchval            int32    `protobuf:"varint,2,opt,name=switchval,proto3" json:"switchval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRequest) Reset()         { *m = AllRequest{} }
func (m *AllRequest) String() string { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()    {}
func (*AllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *AllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRequest.Unmarshal(m, b)
}
func (m *AllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRequest.Marshal(b, m, deterministic)
}
func (m *AllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRequest.Merge(m, src)
}
func (m *AllRequest) XXX_Size() int {
	return xxx_messageInfo_AllRequest.Size(m)
}
func (m *AllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllRequest proto.InternalMessageInfo

func (m *AllRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *AllRequest) GetSwitchval() int32 {
	if m != nil {
		return m.Switchval
	}
	return 0
}

type AllResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllResponse) Reset()         { *m = AllResponse{} }
func (m *AllResponse) String() string { return proto.CompactTextString(m) }
func (*AllResponse) ProtoMessage()    {}
func (*AllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *AllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllResponse.Unmarshal(m, b)
}
func (m *AllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllResponse.Marshal(b, m, deterministic)
}
func (m *AllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllResponse.Merge(m, src)
}
func (m *AllResponse) XXX_Size() int {
	return xxx_messageInfo_AllResponse.Size(m)
}
func (m *AllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllResponse proto.InternalMessageInfo

func (m *AllResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AllResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FriendRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	FriendOpenId         string   `protobuf:"bytes,2,opt,name=friendOpenId,proto3" json:"friendOpenId,omitempty"`
	Switchval            int32    `protobuf:"varint,3,opt,name=switchval,proto3" json:"switchval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendRequest) Reset()         { *m = FriendRequest{} }
func (m *FriendRequest) String() string { return proto.CompactTextString(m) }
func (*FriendRequest) ProtoMessage()    {}
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{2}
}

func (m *FriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendRequest.Unmarshal(m, b)
}
func (m *FriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendRequest.Marshal(b, m, deterministic)
}
func (m *FriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendRequest.Merge(m, src)
}
func (m *FriendRequest) XXX_Size() int {
	return xxx_messageInfo_FriendRequest.Size(m)
}
func (m *FriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendRequest proto.InternalMessageInfo

func (m *FriendRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *FriendRequest) GetFriendOpenId() string {
	if m != nil {
		return m.FriendOpenId
	}
	return ""
}

func (m *FriendRequest) GetSwitchval() int32 {
	if m != nil {
		return m.Switchval
	}
	return 0
}

type GetMyFriendsRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyFriendsRequest) Reset()         { *m = GetMyFriendsRequest{} }
func (m *GetMyFriendsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMyFriendsRequest) ProtoMessage()    {}
func (*GetMyFriendsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{3}
}

func (m *GetMyFriendsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyFriendsRequest.Unmarshal(m, b)
}
func (m *GetMyFriendsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyFriendsRequest.Marshal(b, m, deterministic)
}
func (m *GetMyFriendsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyFriendsRequest.Merge(m, src)
}
func (m *GetMyFriendsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMyFriendsRequest.Size(m)
}
func (m *GetMyFriendsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyFriendsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyFriendsRequest proto.InternalMessageInfo

func (m *GetMyFriendsRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

type GetMyFriendsResponse struct {
	List                 []*GetMyFriendsResponseList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetMyFriendsResponse) Reset()         { *m = GetMyFriendsResponse{} }
func (m *GetMyFriendsResponse) String() string { return proto.CompactTextString(m) }
func (*GetMyFriendsResponse) ProtoMessage()    {}
func (*GetMyFriendsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{4}
}

func (m *GetMyFriendsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyFriendsResponse.Unmarshal(m, b)
}
func (m *GetMyFriendsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyFriendsResponse.Marshal(b, m, deterministic)
}
func (m *GetMyFriendsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyFriendsResponse.Merge(m, src)
}
func (m *GetMyFriendsResponse) XXX_Size() int {
	return xxx_messageInfo_GetMyFriendsResponse.Size(m)
}
func (m *GetMyFriendsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyFriendsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyFriendsResponse proto.InternalMessageInfo

func (m *GetMyFriendsResponse) GetList() []*GetMyFriendsResponseList {
	if m != nil {
		return m.List
	}
	return nil
}

type GetMyFriendsResponseList struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OpenId               string   `protobuf:"bytes,2,opt,name=openId,proto3" json:"openId,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	HeadImgUrl           string   `protobuf:"bytes,5,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	IsBlock              int32    `protobuf:"varint,6,opt,name=isBlock,proto3" json:"isBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyFriendsResponseList) Reset()         { *m = GetMyFriendsResponseList{} }
func (m *GetMyFriendsResponseList) String() string { return proto.CompactTextString(m) }
func (*GetMyFriendsResponseList) ProtoMessage()    {}
func (*GetMyFriendsResponseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{5}
}

func (m *GetMyFriendsResponseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyFriendsResponseList.Unmarshal(m, b)
}
func (m *GetMyFriendsResponseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyFriendsResponseList.Marshal(b, m, deterministic)
}
func (m *GetMyFriendsResponseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyFriendsResponseList.Merge(m, src)
}
func (m *GetMyFriendsResponseList) XXX_Size() int {
	return xxx_messageInfo_GetMyFriendsResponseList.Size(m)
}
func (m *GetMyFriendsResponseList) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyFriendsResponseList.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyFriendsResponseList proto.InternalMessageInfo

func (m *GetMyFriendsResponseList) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetMyFriendsResponseList) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *GetMyFriendsResponseList) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetMyFriendsResponseList) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *GetMyFriendsResponseList) GetHeadImgUrl() string {
	if m != nil {
		return m.HeadImgUrl
	}
	return ""
}

func (m *GetMyFriendsResponseList) GetIsBlock() int32 {
	if m != nil {
		return m.IsBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*AllRequest)(nil), "protos.allRequest")
	proto.RegisterType((*AllResponse)(nil), "protos.allResponse")
	proto.RegisterType((*FriendRequest)(nil), "protos.friendRequest")
	proto.RegisterType((*GetMyFriendsRequest)(nil), "protos.GetMyFriendsRequest")
	proto.RegisterType((*GetMyFriendsResponse)(nil), "protos.GetMyFriendsResponse")
	proto.RegisterType((*GetMyFriendsResponseList)(nil), "protos.GetMyFriendsResponseList")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xa6, 0x94, 0xf6, 0xde, 0x1e, 0xb8, 0xc9, 0xcd, 0x70, 0xaf, 0x99, 0x20, 0x31, 0xcd, 0xac,
	0xd8, 0x48, 0x0c, 0x1a, 0x37, 0xee, 0x58, 0x68, 0x88, 0x18, 0x93, 0x31, 0x3e, 0x40, 0x69, 0x8f,
	0x30, 0x61, 0x68, 0xb1, 0x53, 0x50, 0x5f, 0xcb, 0x77, 0xf0, 0xbd, 0x4c, 0x67, 0x5a, 0xa1, 0x06,
	0x64, 0xd5, 0xf3, 0x9d, 0x7e, 0xe7, 0x9b, 0xef, 0xfc, 0x40, 0x73, 0x22, 0x93, 0x70, 0xde, 0x5f,
	0xa6, 0x49, 0x96, 0x10, 0x57, 0x7f, 0x14, 0x1b, 0x02, 0x04, 0x52, 0x72, 0x7c, 0x5e, 0xa1, 0xca,
	0xc8, 0x11, 0xb8, 0xc9, 0x12, 0xe3, 0x51, 0x44, 0x2d, 0xdf, 0xea, 0x79, 0xbc, 0x40, 0xa4, 0x0b,
	0x9e, 0x7a, 0x11, 0x59, 0x38, 0x5b, 0x07, 0x92, 0xd6, 0x7d, 0xab, 0xe7, 0xf0, 0x4d, 0x82, 0x5d,
	0x41, 0x53, 0x6b, 0xa8, 0x65, 0x12, 0x2b, 0x24, 0x04, 0x1a, 0x61, 0x12, 0xa1, 0x96, 0x70, 0xb8,
	0x8e, 0x09, 0x85, 0x5f, 0x0b, 0x54, 0x2a, 0x98, 0xa2, 0x2e, 0xf7, 0x78, 0x09, 0x99, 0x80, 0x3f,
	0x4f, 0xa9, 0xc0, 0x38, 0x3a, 0xe4, 0x81, 0x41, 0xcb, 0x10, 0xef, 0xcd, 0x5f, 0xa3, 0x53, 0xc9,
	0x55, 0x7d, 0xda, 0xdf, 0x7d, 0x9e, 0x42, 0xfb, 0x06, 0xb3, 0xbb, 0xb7, 0x6b, 0x5d, 0xa2, 0x0e,
	0x3c, 0xc8, 0xc6, 0xf0, 0xaf, 0x4a, 0x2f, 0xfa, 0xbb, 0x80, 0x86, 0x14, 0x2a, 0xa3, 0x96, 0x6f,
	0xf7, 0x9a, 0x03, 0xdf, 0x0c, 0x54, 0xf5, 0x77, 0x71, 0xc7, 0x42, 0x65, 0x5c, 0xb3, 0xd9, 0xbb,
	0x05, 0x74, 0x1f, 0x25, 0xb7, 0xb0, 0x52, 0x98, 0x16, 0x16, 0x1c, 0x5e, 0xa0, 0x2d, 0x6b, 0xf5,
	0xca, 0x2c, 0x3a, 0xf0, 0x3b, 0x16, 0xe1, 0x3c, 0x0e, 0x16, 0xa8, 0xdb, 0xf4, 0xf8, 0x17, 0x26,
	0x7f, 0xc1, 0x56, 0xf8, 0x4a, 0x1b, 0x5a, 0x28, 0x0f, 0xc9, 0x09, 0xc0, 0x0c, 0x83, 0x68, 0xb4,
	0x98, 0x3e, 0xa6, 0x92, 0x3a, 0x9a, 0xbf, 0x95, 0xc9, 0x97, 0x23, 0xd4, 0x30, 0x3f, 0x0e, 0xea,
	0xea, 0xaa, 0x12, 0x0e, 0x3e, 0x2c, 0x68, 0xe9, 0xe8, 0x01, 0xd3, 0xb5, 0x08, 0x91, 0x9c, 0x81,
	0x1d, 0x48, 0x49, 0x48, 0xd9, 0xf4, 0xe6, 0x76, 0x3a, 0xed, 0x4a, 0xce, 0x34, 0xc7, 0x6a, 0xe4,
	0x12, 0x5c, 0xb3, 0x22, 0xf2, 0xbf, 0x24, 0x54, 0xf6, 0xbd, 0xaf, 0xee, 0x16, 0x5a, 0xdb, 0xe3,
	0x22, 0xc7, 0xbb, 0xe7, 0x6c, 0x34, 0xba, 0x3f, 0x2d, 0x81, 0xd5, 0x26, 0xe6, 0xda, 0xcf, 0x3f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xfb, 0x78, 0xd9, 0x03, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockServiceClient is the client API for BlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockServiceClient interface {
	All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllResponse, error)
	Friend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*AllResponse, error)
	GetMyFriends(ctx context.Context, in *GetMyFriendsRequest, opts ...grpc.CallOption) (*GetMyFriendsResponse, error)
}

type blockServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlockServiceClient(cc *grpc.ClientConn) BlockServiceClient {
	return &blockServiceClient{cc}
}

func (c *blockServiceClient) All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllResponse, error) {
	out := new(AllResponse)
	err := c.cc.Invoke(ctx, "/protos.BlockService/all", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockServiceClient) Friend(ctx context.Context, in *FriendRequest, opts ...grpc.CallOption) (*AllResponse, error) {
	out := new(AllResponse)
	err := c.cc.Invoke(ctx, "/protos.BlockService/friend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockServiceClient) GetMyFriends(ctx context.Context, in *GetMyFriendsRequest, opts ...grpc.CallOption) (*GetMyFriendsResponse, error) {
	out := new(GetMyFriendsResponse)
	err := c.cc.Invoke(ctx, "/protos.BlockService/GetMyFriends", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockServiceServer is the server API for BlockService service.
type BlockServiceServer interface {
	All(context.Context, *AllRequest) (*AllResponse, error)
	Friend(context.Context, *FriendRequest) (*AllResponse, error)
	GetMyFriends(context.Context, *GetMyFriendsRequest) (*GetMyFriendsResponse, error)
}

// UnimplementedBlockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBlockServiceServer struct {
}

func (*UnimplementedBlockServiceServer) All(ctx context.Context, req *AllRequest) (*AllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method All not implemented")
}
func (*UnimplementedBlockServiceServer) Friend(ctx context.Context, req *FriendRequest) (*AllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Friend not implemented")
}
func (*UnimplementedBlockServiceServer) GetMyFriends(ctx context.Context, req *GetMyFriendsRequest) (*GetMyFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyFriends not implemented")
}

func RegisterBlockServiceServer(s *grpc.Server, srv BlockServiceServer) {
	s.RegisterService(&_BlockService_serviceDesc, srv)
}

func _BlockService_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BlockService/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).All(ctx, req.(*AllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockService_Friend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).Friend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BlockService/Friend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).Friend(ctx, req.(*FriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockService_GetMyFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockServiceServer).GetMyFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.BlockService/GetMyFriends",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockServiceServer).GetMyFriends(ctx, req.(*GetMyFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.BlockService",
	HandlerType: (*BlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "all",
			Handler:    _BlockService_All_Handler,
		},
		{
			MethodName: "friend",
			Handler:    _BlockService_Friend_Handler,
		},
		{
			MethodName: "GetMyFriends",
			Handler:    _BlockService_GetMyFriends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "block.proto",
}
