// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//根据用户openid查询用户信息
type GetUserByOpenidRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByOpenidRequest) Reset()         { *m = GetUserByOpenidRequest{} }
func (m *GetUserByOpenidRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByOpenidRequest) ProtoMessage()    {}
func (*GetUserByOpenidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetUserByOpenidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByOpenidRequest.Unmarshal(m, b)
}
func (m *GetUserByOpenidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByOpenidRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByOpenidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByOpenidRequest.Merge(m, src)
}
func (m *GetUserByOpenidRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByOpenidRequest.Size(m)
}
func (m *GetUserByOpenidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByOpenidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByOpenidRequest proto.InternalMessageInfo

func (m *GetUserByOpenidRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

type GetUserByOpenidResponse struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OpenId               string   `protobuf:"bytes,2,opt,name=openId,proto3" json:"openId,omitempty"`
	UnionId              string   `protobuf:"bytes,3,opt,name=unionId,proto3" json:"unionId,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Province             string   `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	HeadImgUrl           string   `protobuf:"bytes,9,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	IsBlock              int32    `protobuf:"varint,10,opt,name=isBlock,proto3" json:"isBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByOpenidResponse) Reset()         { *m = GetUserByOpenidResponse{} }
func (m *GetUserByOpenidResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByOpenidResponse) ProtoMessage()    {}
func (*GetUserByOpenidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetUserByOpenidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByOpenidResponse.Unmarshal(m, b)
}
func (m *GetUserByOpenidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByOpenidResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByOpenidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByOpenidResponse.Merge(m, src)
}
func (m *GetUserByOpenidResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByOpenidResponse.Size(m)
}
func (m *GetUserByOpenidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByOpenidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByOpenidResponse proto.InternalMessageInfo

func (m *GetUserByOpenidResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserByOpenidResponse) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *GetUserByOpenidResponse) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *GetUserByOpenidResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetUserByOpenidResponse) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *GetUserByOpenidResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *GetUserByOpenidResponse) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *GetUserByOpenidResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GetUserByOpenidResponse) GetHeadImgUrl() string {
	if m != nil {
		return m.HeadImgUrl
	}
	return ""
}

func (m *GetUserByOpenidResponse) GetIsBlock() int32 {
	if m != nil {
		return m.IsBlock
	}
	return 0
}

//批量查询，根据用户openid查询用户信息
type GetUsersByOpenidsRequest struct {
	OpenIds              string   `protobuf:"bytes,1,opt,name=openIds,proto3" json:"openIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersByOpenidsRequest) Reset()         { *m = GetUsersByOpenidsRequest{} }
func (m *GetUsersByOpenidsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersByOpenidsRequest) ProtoMessage()    {}
func (*GetUsersByOpenidsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUsersByOpenidsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByOpenidsRequest.Unmarshal(m, b)
}
func (m *GetUsersByOpenidsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByOpenidsRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersByOpenidsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByOpenidsRequest.Merge(m, src)
}
func (m *GetUsersByOpenidsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersByOpenidsRequest.Size(m)
}
func (m *GetUsersByOpenidsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByOpenidsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByOpenidsRequest proto.InternalMessageInfo

func (m *GetUsersByOpenidsRequest) GetOpenIds() string {
	if m != nil {
		return m.OpenIds
	}
	return ""
}

type GetUsersByOpenidsResponse struct {
	List                 []*GetUserByOpenidResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetUsersByOpenidsResponse) Reset()         { *m = GetUsersByOpenidsResponse{} }
func (m *GetUsersByOpenidsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersByOpenidsResponse) ProtoMessage()    {}
func (*GetUsersByOpenidsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetUsersByOpenidsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByOpenidsResponse.Unmarshal(m, b)
}
func (m *GetUsersByOpenidsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByOpenidsResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersByOpenidsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByOpenidsResponse.Merge(m, src)
}
func (m *GetUsersByOpenidsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersByOpenidsResponse.Size(m)
}
func (m *GetUsersByOpenidsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByOpenidsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByOpenidsResponse proto.InternalMessageInfo

func (m *GetUsersByOpenidsResponse) GetList() []*GetUserByOpenidResponse {
	if m != nil {
		return m.List
	}
	return nil
}

//保存用户信息
type SaveUserRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	UnionId              string   `protobuf:"bytes,2,opt,name=unionId,proto3" json:"unionId,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Province             string   `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	Country              string   `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	HeadImgUrl           string   `protobuf:"bytes,8,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	FriendOpenId         string   `protobuf:"bytes,9,opt,name=FriendOpenId,proto3" json:"FriendOpenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserRequest) Reset()         { *m = SaveUserRequest{} }
func (m *SaveUserRequest) String() string { return proto.CompactTextString(m) }
func (*SaveUserRequest) ProtoMessage()    {}
func (*SaveUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *SaveUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserRequest.Unmarshal(m, b)
}
func (m *SaveUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserRequest.Marshal(b, m, deterministic)
}
func (m *SaveUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserRequest.Merge(m, src)
}
func (m *SaveUserRequest) XXX_Size() int {
	return xxx_messageInfo_SaveUserRequest.Size(m)
}
func (m *SaveUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserRequest proto.InternalMessageInfo

func (m *SaveUserRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *SaveUserRequest) GetUnionId() string {
	if m != nil {
		return m.UnionId
	}
	return ""
}

func (m *SaveUserRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SaveUserRequest) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *SaveUserRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SaveUserRequest) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *SaveUserRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SaveUserRequest) GetHeadImgUrl() string {
	if m != nil {
		return m.HeadImgUrl
	}
	return ""
}

func (m *SaveUserRequest) GetFriendOpenId() string {
	if m != nil {
		return m.FriendOpenId
	}
	return ""
}

type SaveUserResponse struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserResponse) Reset()         { *m = SaveUserResponse{} }
func (m *SaveUserResponse) String() string { return proto.CompactTextString(m) }
func (*SaveUserResponse) ProtoMessage()    {}
func (*SaveUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *SaveUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserResponse.Unmarshal(m, b)
}
func (m *SaveUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserResponse.Marshal(b, m, deterministic)
}
func (m *SaveUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserResponse.Merge(m, src)
}
func (m *SaveUserResponse) XXX_Size() int {
	return xxx_messageInfo_SaveUserResponse.Size(m)
}
func (m *SaveUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserResponse proto.InternalMessageInfo

func (m *SaveUserResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

//取消订阅
type UnsubscribeRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

func (m *UnsubscribeRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

type UnsubscribeResponse struct {
	Success              int32    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeResponse) Reset()         { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()    {}
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UnsubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeResponse.Unmarshal(m, b)
}
func (m *UnsubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeResponse.Marshal(b, m, deterministic)
}
func (m *UnsubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeResponse.Merge(m, src)
}
func (m *UnsubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeResponse.Size(m)
}
func (m *UnsubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeResponse proto.InternalMessageInfo

func (m *UnsubscribeResponse) GetSuccess() int32 {
	if m != nil {
		return m.Success
	}
	return 0
}

func init() {
	proto.RegisterType((*GetUserByOpenidRequest)(nil), "protos.GetUserByOpenidRequest")
	proto.RegisterType((*GetUserByOpenidResponse)(nil), "protos.GetUserByOpenidResponse")
	proto.RegisterType((*GetUsersByOpenidsRequest)(nil), "protos.GetUsersByOpenidsRequest")
	proto.RegisterType((*GetUsersByOpenidsResponse)(nil), "protos.GetUsersByOpenidsResponse")
	proto.RegisterType((*SaveUserRequest)(nil), "protos.SaveUserRequest")
	proto.RegisterType((*SaveUserResponse)(nil), "protos.SaveUserResponse")
	proto.RegisterType((*UnsubscribeRequest)(nil), "protos.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeResponse)(nil), "protos.UnsubscribeResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xc9, 0xdf, 0x4d, 0x27, 0x48, 0x2d, 0x46, 0x6a, 0xcd, 0x22, 0x95, 0xe0, 0x53, 0x85,
	0x50, 0x41, 0x2d, 0x77, 0xa4, 0x1e, 0x80, 0x9e, 0x8a, 0x52, 0x72, 0xe1, 0x96, 0x38, 0x23, 0xb0,
	0x9a, 0xda, 0x8b, 0x67, 0x37, 0x22, 0x0f, 0xc2, 0x4b, 0xf1, 0x52, 0x20, 0x7b, 0xed, 0x74, 0x9b,
	0xcd, 0x26, 0xa7, 0xec, 0xe7, 0x99, 0xf9, 0xc6, 0xfe, 0xcd, 0x28, 0x00, 0x05, 0xa1, 0x3d, 0xcf,
	0xac, 0xc9, 0x0d, 0xeb, 0xfb, 0x1f, 0x12, 0xef, 0xe1, 0xf8, 0x33, 0xe6, 0x13, 0x42, 0x7b, 0xb5,
	0xba, 0xc9, 0x50, 0xab, 0xf9, 0x18, 0x7f, 0x15, 0x48, 0x39, 0x3b, 0x86, 0xbe, 0xc9, 0x50, 0x5f,
	0xcf, 0x79, 0x6b, 0xd4, 0x3a, 0x3b, 0x18, 0x07, 0x25, 0xfe, 0xb4, 0xe1, 0xa4, 0x56, 0x42, 0x99,
	0xd1, 0x84, 0xae, 0xc6, 0xf5, 0x08, 0x35, 0xbd, 0x71, 0x50, 0x15, 0xaf, 0x76, 0xd5, 0x8b, 0x71,
	0x48, 0x0a, 0xad, 0x8c, 0x0b, 0x74, 0x7c, 0x20, 0x4a, 0x96, 0xc2, 0x40, 0x2b, 0x79, 0xa7, 0xa7,
	0xf7, 0xc8, 0xbb, 0x3e, 0xb4, 0xd6, 0xec, 0x08, 0x3a, 0x84, 0xbf, 0x79, 0xcf, 0xb7, 0x70, 0x9f,
	0x8c, 0x41, 0x57, 0xaa, 0x7c, 0xc5, 0xfb, 0x3e, 0xd3, 0x7f, 0x3b, 0x87, 0xcc, 0x9a, 0xa5, 0xd2,
	0x12, 0x79, 0x52, 0x3a, 0x44, 0xed, 0xfa, 0x4a, 0x53, 0xe8, 0xdc, 0xae, 0xf8, 0xa0, 0xec, 0x1b,
	0x24, 0x3b, 0x05, 0xf8, 0x89, 0xd3, 0xf9, 0xf5, 0xfd, 0x8f, 0x89, 0x5d, 0xf0, 0x03, 0x1f, 0xac,
	0x9c, 0xb8, 0x4a, 0x45, 0x57, 0x0b, 0x23, 0xef, 0x38, 0xf8, 0xfe, 0x51, 0x8a, 0x0f, 0xc0, 0x03,
	0x16, 0x8a, 0x5c, 0x28, 0xb2, 0xe4, 0x90, 0x94, 0x2f, 0xa6, 0x00, 0x33, 0x4a, 0xf1, 0x15, 0x5e,
	0x6c, 0xa9, 0x0a, 0x38, 0x2f, 0xa1, 0xbb, 0x50, 0x94, 0xf3, 0xd6, 0xa8, 0x73, 0x36, 0xbc, 0x78,
	0x55, 0x8e, 0x8e, 0xce, 0x1b, 0xe8, 0x8f, 0x7d, 0xb2, 0xf8, 0xd7, 0x82, 0xc3, 0xdb, 0xe9, 0x12,
	0x5d, 0xca, 0x9e, 0x59, 0x56, 0xf9, 0xb7, 0x9b, 0xf9, 0x77, 0xb6, 0xf3, 0xef, 0xd6, 0xf9, 0xf7,
	0x1a, 0xf8, 0xf7, 0x9b, 0xf9, 0x27, 0xbb, 0xf8, 0x0f, 0x6a, 0xfc, 0x05, 0x3c, 0xfd, 0x64, 0x15,
	0xea, 0xf9, 0x4d, 0xf9, 0x9e, 0x72, 0x42, 0x8f, 0xce, 0xc4, 0x1b, 0x38, 0x7a, 0x00, 0xb0, 0x7b,
	0x33, 0xc5, 0x5b, 0x60, 0x13, 0x4d, 0xc5, 0x8c, 0xa4, 0x55, 0x33, 0xdc, 0xb7, 0xfb, 0xef, 0xe0,
	0xf9, 0xa3, 0xec, 0x60, 0xce, 0x21, 0xa1, 0x42, 0x4a, 0x24, 0x0a, 0xee, 0x51, 0x5e, 0xfc, 0x6d,
	0xc3, 0xd0, 0xdd, 0xe3, 0x16, 0xed, 0x52, 0x49, 0x64, 0xdf, 0xe0, 0x70, 0x63, 0x7a, 0xec, 0xb4,
	0x71, 0xac, 0xfe, 0x2e, 0xe9, 0xbe, 0xb1, 0x8b, 0x27, 0xec, 0x3b, 0x3c, 0xab, 0x2d, 0x11, 0x1b,
	0x6d, 0xd4, 0xd5, 0xb6, 0x32, 0x7d, 0xbd, 0x23, 0x63, 0xed, 0xfd, 0x11, 0x06, 0x11, 0x26, 0x3b,
	0x89, 0x05, 0x1b, 0xfb, 0x95, 0xf2, 0x7a, 0x60, 0x6d, 0xf0, 0x05, 0x86, 0x15, 0x66, 0x2c, 0x8d,
	0xa9, 0x75, 0xec, 0xe9, 0xcb, 0xad, 0xb1, 0xe8, 0x34, 0x2b, 0xff, 0xb3, 0x2e, 0xff, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x99, 0xcd, 0xec, 0x06, 0xc8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUserByOpenid(ctx context.Context, in *GetUserByOpenidRequest, opts ...grpc.CallOption) (*GetUserByOpenidResponse, error)
	GetUsersByOpenids(ctx context.Context, in *GetUsersByOpenidsRequest, opts ...grpc.CallOption) (*GetUsersByOpenidsResponse, error)
	SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUserByOpenid(ctx context.Context, in *GetUserByOpenidRequest, opts ...grpc.CallOption) (*GetUserByOpenidResponse, error) {
	out := new(GetUserByOpenidResponse)
	err := c.cc.Invoke(ctx, "/protos.UserService/GetUserByOpenid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsersByOpenids(ctx context.Context, in *GetUsersByOpenidsRequest, opts ...grpc.CallOption) (*GetUsersByOpenidsResponse, error) {
	out := new(GetUsersByOpenidsResponse)
	err := c.cc.Invoke(ctx, "/protos.UserService/GetUsersByOpenids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error) {
	out := new(SaveUserResponse)
	err := c.cc.Invoke(ctx, "/protos.UserService/SaveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, "/protos.UserService/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUserByOpenid(context.Context, *GetUserByOpenidRequest) (*GetUserByOpenidResponse, error)
	GetUsersByOpenids(context.Context, *GetUsersByOpenidsRequest) (*GetUsersByOpenidsResponse, error)
	SaveUser(context.Context, *SaveUserRequest) (*SaveUserResponse, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUserByOpenid(ctx context.Context, req *GetUserByOpenidRequest) (*GetUserByOpenidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByOpenid not implemented")
}
func (*UnimplementedUserServiceServer) GetUsersByOpenids(ctx context.Context, req *GetUsersByOpenidsRequest) (*GetUsersByOpenidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByOpenids not implemented")
}
func (*UnimplementedUserServiceServer) SaveUser(ctx context.Context, req *SaveUserRequest) (*SaveUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUser not implemented")
}
func (*UnimplementedUserServiceServer) Unsubscribe(ctx context.Context, req *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUserByOpenid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByOpenidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByOpenid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserService/GetUserByOpenid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByOpenid(ctx, req.(*GetUserByOpenidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsersByOpenids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByOpenidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsersByOpenids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserService/GetUsersByOpenids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsersByOpenids(ctx, req.(*GetUsersByOpenidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SaveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SaveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserService/SaveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SaveUser(ctx, req.(*SaveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserService/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByOpenid",
			Handler:    _UserService_GetUserByOpenid_Handler,
		},
		{
			MethodName: "GetUsersByOpenids",
			Handler:    _UserService_GetUsersByOpenids_Handler,
		},
		{
			MethodName: "SaveUser",
			Handler:    _UserService_SaveUser_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _UserService_Unsubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
