// Code generated by protoc-gen-go. DO NOT EDIT.
// source: water.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWaterTextRequest struct {
	WaterTime            string   `protobuf:"bytes,1,opt,name=waterTime,proto3" json:"waterTime,omitempty"`
	LastUserId           int32    `protobuf:"varint,2,opt,name=lastUserId,proto3" json:"lastUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWaterTextRequest) Reset()         { *m = GetWaterTextRequest{} }
func (m *GetWaterTextRequest) String() string { return proto.CompactTextString(m) }
func (*GetWaterTextRequest) ProtoMessage()    {}
func (*GetWaterTextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{0}
}

func (m *GetWaterTextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWaterTextRequest.Unmarshal(m, b)
}
func (m *GetWaterTextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWaterTextRequest.Marshal(b, m, deterministic)
}
func (m *GetWaterTextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWaterTextRequest.Merge(m, src)
}
func (m *GetWaterTextRequest) XXX_Size() int {
	return xxx_messageInfo_GetWaterTextRequest.Size(m)
}
func (m *GetWaterTextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWaterTextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWaterTextRequest proto.InternalMessageInfo

func (m *GetWaterTextRequest) GetWaterTime() string {
	if m != nil {
		return m.WaterTime
	}
	return ""
}

func (m *GetWaterTextRequest) GetLastUserId() int32 {
	if m != nil {
		return m.LastUserId
	}
	return 0
}

type GetWaterTextResponse struct {
	List                 []*List  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWaterTextResponse) Reset()         { *m = GetWaterTextResponse{} }
func (m *GetWaterTextResponse) String() string { return proto.CompactTextString(m) }
func (*GetWaterTextResponse) ProtoMessage()    {}
func (*GetWaterTextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{1}
}

func (m *GetWaterTextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWaterTextResponse.Unmarshal(m, b)
}
func (m *GetWaterTextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWaterTextResponse.Marshal(b, m, deterministic)
}
func (m *GetWaterTextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWaterTextResponse.Merge(m, src)
}
func (m *GetWaterTextResponse) XXX_Size() int {
	return xxx_messageInfo_GetWaterTextResponse.Size(m)
}
func (m *GetWaterTextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWaterTextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWaterTextResponse proto.InternalMessageInfo

func (m *GetWaterTextResponse) GetList() []*List {
	if m != nil {
		return m.List
	}
	return nil
}

type List struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OpenId               string   `protobuf:"bytes,2,opt,name=openId,proto3" json:"openId,omitempty"`
	WaterText            string   `protobuf:"bytes,3,opt,name=waterText,proto3" json:"waterText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{2}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *List) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *List) GetWaterText() string {
	if m != nil {
		return m.WaterText
	}
	return ""
}

type GetRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

type GetResponse struct {
	Waterval             int32    `protobuf:"varint,1,opt,name=waterval,proto3" json:"waterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetWaterval() int32 {
	if m != nil {
		return m.Waterval
	}
	return 0
}

type SetRequest struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=openId,proto3" json:"openId,omitempty"`
	Waterval             int32    `protobuf:"varint,2,opt,name=waterval,proto3" json:"waterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{5}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *SetRequest) GetWaterval() int32 {
	if m != nil {
		return m.Waterval
	}
	return 0
}

type SetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c895fc20b6ed18c2, []int{6}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetWaterTextRequest)(nil), "protos.getWaterTextRequest")
	proto.RegisterType((*GetWaterTextResponse)(nil), "protos.getWaterTextResponse")
	proto.RegisterType((*List)(nil), "protos.List")
	proto.RegisterType((*GetRequest)(nil), "protos.getRequest")
	proto.RegisterType((*GetResponse)(nil), "protos.getResponse")
	proto.RegisterType((*SetRequest)(nil), "protos.setRequest")
	proto.RegisterType((*SetResponse)(nil), "protos.setResponse")
}

func init() { proto.RegisterFile("water.proto", fileDescriptor_c895fc20b6ed18c2) }

var fileDescriptor_c895fc20b6ed18c2 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x4f, 0xbb, 0x40,
	0x10, 0xc5, 0xff, 0x5b, 0xfa, 0x6f, 0x64, 0xc0, 0xcb, 0xd6, 0x18, 0x52, 0x1b, 0x43, 0x36, 0x1e,
	0xf0, 0xd2, 0x98, 0x7a, 0xf1, 0xe8, 0xd5, 0xe8, 0x89, 0x62, 0x3c, 0xa3, 0x4e, 0x08, 0x09, 0x16,
	0x64, 0xa6, 0x95, 0x6f, 0xe7, 0x57, 0x33, 0x2c, 0xdb, 0xb2, 0x18, 0x12, 0x4f, 0x64, 0xde, 0xcc,
	0xfb, 0xcd, 0x63, 0x00, 0xbc, 0xaf, 0x94, 0xb1, 0x5e, 0x55, 0x75, 0xc9, 0xa5, 0x9c, 0xe9, 0x07,
	0xa9, 0x0d, 0xcc, 0x33, 0xe4, 0x97, 0xb6, 0x93, 0x60, 0xc3, 0x31, 0x7e, 0xee, 0x90, 0x58, 0x2e,
	0xc1, 0xd5, 0xd3, 0x49, 0xfe, 0x81, 0x81, 0x08, 0x45, 0xe4, 0xc6, 0xbd, 0x20, 0x2f, 0x01, 0x8a,
	0x94, 0xf8, 0x99, 0xb0, 0x7e, 0x78, 0x0f, 0x26, 0xa1, 0x88, 0xfe, 0xc7, 0x96, 0xa2, 0xee, 0xe0,
	0x6c, 0x08, 0xa5, 0xaa, 0xdc, 0x12, 0xca, 0x10, 0xa6, 0x45, 0x4e, 0x1c, 0x88, 0xd0, 0x89, 0xbc,
	0xb5, 0xdf, 0x45, 0xa1, 0xd5, 0x53, 0x4e, 0x1c, 0xeb, 0x8e, 0x4a, 0x60, 0xda, 0x56, 0xf2, 0x1c,
	0x66, 0xbb, 0x8e, 0x2e, 0x34, 0xdd, 0x54, 0xad, 0x5e, 0x56, 0xb8, 0x35, 0x5b, 0xdd, 0xd8, 0x54,
	0x7d, 0x5e, 0x6c, 0x38, 0x70, 0xec, 0xbc, 0xd8, 0xb0, 0xba, 0x02, 0xc8, 0xf0, 0xf8, 0x6e, 0x3d,
	0x43, 0xd8, 0x0c, 0x75, 0x0d, 0x9e, 0x9e, 0x32, 0x61, 0x17, 0x70, 0xa2, 0x09, 0xfb, 0xb4, 0x30,
	0x21, 0x8e, 0xb5, 0xba, 0x07, 0xa0, 0x3f, 0x81, 0x03, 0xc2, 0xe4, 0x17, 0xe1, 0x14, 0x3c, 0xea,
	0x97, 0xad, 0xbf, 0x05, 0xf8, 0xfa, 0x5e, 0x1b, 0xac, 0xf7, 0xf9, 0x1b, 0xca, 0x47, 0xf0, 0xed,
	0x13, 0xca, 0x8b, 0xc3, 0xb1, 0x46, 0xbe, 0xd6, 0x62, 0x39, 0xde, 0xec, 0xd8, 0xea, 0x9f, 0xbc,
	0x01, 0x27, 0x43, 0x96, 0xd2, 0x1a, 0x3b, 0x58, 0xe7, 0x03, 0xcd, 0x76, 0x90, 0xed, 0xa0, 0x11,
	0x07, 0xd9, 0x8e, 0xd7, 0xee, 0x87, 0xba, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xf6, 0x24,
	0xab, 0x66, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WaterServiceClient is the client API for WaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WaterServiceClient interface {
	GetWaterText(ctx context.Context, in *GetWaterTextRequest, opts ...grpc.CallOption) (*GetWaterTextResponse, error)
	//获得开关值
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	//设置开关
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type waterServiceClient struct {
	cc *grpc.ClientConn
}

func NewWaterServiceClient(cc *grpc.ClientConn) WaterServiceClient {
	return &waterServiceClient{cc}
}

func (c *waterServiceClient) GetWaterText(ctx context.Context, in *GetWaterTextRequest, opts ...grpc.CallOption) (*GetWaterTextResponse, error) {
	out := new(GetWaterTextResponse)
	err := c.cc.Invoke(ctx, "/protos.WaterService/getWaterText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waterServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/protos.WaterService/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waterServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/protos.WaterService/set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaterServiceServer is the server API for WaterService service.
type WaterServiceServer interface {
	GetWaterText(context.Context, *GetWaterTextRequest) (*GetWaterTextResponse, error)
	//获得开关值
	Get(context.Context, *GetRequest) (*GetResponse, error)
	//设置开关
	Set(context.Context, *SetRequest) (*SetResponse, error)
}

// UnimplementedWaterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWaterServiceServer struct {
}

func (*UnimplementedWaterServiceServer) GetWaterText(ctx context.Context, req *GetWaterTextRequest) (*GetWaterTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWaterText not implemented")
}
func (*UnimplementedWaterServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedWaterServiceServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}

func RegisterWaterServiceServer(s *grpc.Server, srv WaterServiceServer) {
	s.RegisterService(&_WaterService_serviceDesc, srv)
}

func _WaterService_GetWaterText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaterTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).GetWaterText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.WaterService/GetWaterText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).GetWaterText(ctx, req.(*GetWaterTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaterService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.WaterService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaterService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.WaterService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WaterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.WaterService",
	HandlerType: (*WaterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getWaterText",
			Handler:    _WaterService_GetWaterText_Handler,
		},
		{
			MethodName: "get",
			Handler:    _WaterService_Get_Handler,
		},
		{
			MethodName: "set",
			Handler:    _WaterService_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "water.proto",
}
